[package]
name = "jerboa"
version = "0.1.0"
edition = "2024"
authors = ["Phil Brooks"]

[profile.release]
panic = 'abort'
lto = true
codegen-units = 1
strip = true

[profile.dev]
overflow-checks = false